name = "aitrustlanding1"
compatibility_date = "2024-01-01"
main = "worker/index.ts"

routes = [
  { pattern = "aitrustaudit.com", custom_domain = true }
]

[build]
command = "npm run build"

[assets]
directory = "./out"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "aitrustaudit-leads"
database_id = "e73d0f7d-d1e9-4f45-a04a-c522f6c2486d"
